### ISSUE TITLE
configure does not work on Debian

### ISSUE THREAD

**Issue by mkminer** [viacoin/viacoin-obsolete#1]
via@hydra:~/viacoin-0.10.3$ ./autogen.sh
configure.ac:13: installing `src/build-aux/config.guess'
configure.ac:13: installing`src/build-aux/config.sub'
configure.ac:38: installing `src/build-aux/install-sh'
configure.ac:38: installing`src/build-aux/missing'
src/Makefile.am: installing `src/build-aux/depcomp'
via@hydra:~/viacoin-0.10.3$ ./configure
./configure: line 2732: syntax error near unexpected token`disable-shared'
./configure: line 2732: `LT_INIT(disable-shared)'

**Comment by btcdrak** [comment]
You havent followed the installation instruction. You didnt install `libtool`.

See: https://github.com/viacoin/viacoin/blob/0.10/doc/build-unix.md#dependency-build-instructions-ubuntu--debian
