### ISSUE TITLE
Fix unit tests

### ISSUE THREAD

**Issue by btcdrak** [viacoin/viacoin-obsolete#10]
Several unit tests fail at the moment. 

In the majority of cases it seems just updating `src/tests/data` will suffice since obviously our key prefixes etc. have changed.

**Comment by GrynnSan** [comment]
yep `src/test/data/alertTests.raw` and its header version `alertTests.raw.h` needs to be recreated with the alert signing  key. The file alert_tests.cpp has the code that creates this data file ifdef'd out , but it also does not provide the function `SignAndSave()` which is the code that actually, wells signs and saves the alert to the file. This it trivial code to write, and the original bitcoin code probably hard-codes their signing key in the file so they chose not to include it in source control.  We have two options: (1) I can rewrite it, and check it in here for Viacoin with the signing key as a command line argument. Having it available will benefit others as well; or (2) we can try to get a sanitized version from one of the core devs (and maybe only Gavin has this ??)

**Comment by btcdrak** [comment]
Best just do it ourselves. Isnt there some code here you can reuse? https://github.com/viacoin/viacoin/blob/master/src/rpcmisc.cpp#L396

**Comment by GrynnSan** [comment]
yes of course I plan to reuse much of the code that already exists for signing alerts in that file... I know it well :)

**Comment by GrynnSan** [comment]
Once it's done you'll need to run the alert generator and give it your new signing key.
