### ISSUE TITLE
[0.10.5] Fee calculations

### ISSUE THREAD

**Issue by btcdrak** [viacoin/viacoin-obsolete#15]
I've had reports of insane fees using Qt client 0.10.5

http://i.imgur.com/VR6rK9X.png
http://i.imgur.com/3SgyXzt.png

**Comment by reorder** [comment]
Is it possible to ask reporter for his addresses to estimate number of inputs he tried to spend?

**Comment by petertodd** [comment]
gmaxwell is doing some work re: fees on bitcoin core: https://github.com/bitcoin/bitcoin/pull/5481

**Comment by ByronAP** [comment]
It was only 1 input

**Comment by btcdrak** [comment]
Fee logic improved upstream.
