### ISSUE TITLE
Enhancement: Add rpc functionality back to viacoind

### ISSUE THREAD

**Issue by sigwo** [viacoin/viacoin-obsolete#25]
The viacoin-cli only is a pain. Please add the RPC client functionality back to the viacoind daemon.

**Comment by btcdrak** [comment]
That would be going against modularity.

**Comment by sigwo** [comment]
Booo! :P

-SG

**Comment by btcdrak** [comment]
FWIW As of the next release of bitcoin, 0.10, it will also be split.

**Comment by sigwo** [comment]
Yea, it used to be split on dogecoin, but they re-integrated the commands.  Now dogecoind does all the dogecoin-cli functions. Just habitual things and hopefully doesn't cause my pool errors. LOL 
Thanks for responding. 
-SG

**Comment by btcdrak** [comment]
@sigwo what pool do you run?

**Comment by sigwo** [comment]
http://bemining.net and http://ihash.co
