### ISSUE TITLE
Two tiny issues after upgrading to 0.10.6.3

### ISSUE THREAD

**Issue by toffoo** [viacoin/viacoin-obsolete#27]
Upgraded directly from 0.10.5, running on OSX 10.9.5:

1.) the thousands separator (a comma) is now inexplicably missing from any number larger than 3 digits anywhere (balance, recent transactions, transaction list, etc.)

2.) you should probably update the time/date on your OSX build machine.  (this is not a new problem, but I just noticed it again.  all file dates/times on all Viacoin builds I've installed are like a year and a half slow)

On a related note, you should probably institute some kind of code security scheme.  Bitcoin-qt OSX releases come with both a GPG-signed SHA1 hash of the .dmg and the binary is code-signed to pass Apple's Gatekeeper system.  Viacoin-qt has neither, but at some point should probably have at least one or both.

Besides that, the reindex went fine and everything seems to be working great.

**Comment by btcdrak** [comment]
Point 1 is intentional, it's scientific notation.

Point 2 the build environment is a gitian vm, I'll look into it.

I agree we should do code signing, but everything is built using gitian builds and thus deterministic. We will publish the binary hashes for independent verification.

**Comment by btcdrak** [comment]
```
e53017c9826ff17d7b52baf1432474545b6499804f5f60312f1e4e96fae8e5e8  viacoin-0.10.6.3.tar.gz
f826344d8261eea0442d06d20e575a4f194a386fed683c0b1483b3edaa818055  viacoin-0.10.6.3-linux.tar.gz
4cf351efaf5148209caadea27919c105095a08506425f6fe9508ae2369bc99af  viacoin-0.10.6.3-win32-setup.exe
87d39a7cfed0e3400e9fa5c955b197522a40cc97e8a27f831ef1ca393f4cd933  viacoin-0.10.6.3-win64-setup.exe
56ae550399b37a5541a198b0a4354c3510a769e986ea45b4f46a607a4fbf5d36  viacoin-0.10.6.3-osx.dmg
```

Signed: https://gist.github.com/btcdrak/cc9e33e678896be757d5
