### ISSUE TITLE
Question!

### ISSUE THREAD

**Issue by geopayme** [viacoin/viacoin-obsolete#36]
I am building an electrum wallet for android... I seen to got something going, I was hoping someone can clarify some of the details. I created the wallet, but I don't see it in the block explorer! Maybe I missed something in the code below?

```
  id = "viacoin.main"; // Do not change this id as wallets serialize this string

    addressHeader = 71;
    p2shHeader = 33;
    acceptableAddressCodes = new int[] { addressHeader, p2shHeader };
    spendableCoinbaseDepth = 100;
    dumpedPrivateKeyHeader = 199; // TODO check value
    name = "VIA (α)";
    symbol = "VIA";
    uriScheme = "viacoin";
    bip44Index = 14;
    unitExponent = 8;
    feePerKb = value(10000);
    minNonDust = value(1000); // 0.00001
    softDustLimit = value(100000); // 0.001
    softDustPolicy = SoftDustPolicy.BASE_FEE_FOR_EACH_SOFT_DUST_TXO;
}
```

**Comment by btcdrak** [comment]
You can find a working Electrum implementation for Viacoin here https://github.com/vialectrum with the relevant details in the code.

**Comment by geopayme** [comment]
Thanks.

**Comment by btcdrak** [comment]
Please keep in touch, and let me know of your progress.

**Comment by geopayme** [comment]
I got the majority of the programming done on the Uberpay wallet, but I
have a bit of trouble on the address not showing up on the block
explorer... I thought maybe some of the parameters I posted earlier may be
wrong

![image](https://cloud.githubusercontent.com/assets/8299759/9902761/942f9a3a-5c79-11e5-8c97-59bc1c818f8b.png)

![image](https://cloud.githubusercontent.com/assets/8299759/9902765/9e06b980-5c79-11e5-9055-d737b926bc5c.png)

![image](https://cloud.githubusercontent.com/assets/8299759/9902768/a4b6a178-5c79-11e5-97f7-d3da2a245321.png)

**Comment by btcdrak** [comment]
By eye, looks like feePerKb is wrong, should be 100000. Dust depends, but 1000 is way too small, more like 56000. spendableCoinbaseDepth is 3600. Come to #viacoin-dev on Freenode if you are having more difficulty.

**Comment by geopayme** [comment]
Hello,

I dont know if its me, here is a viacoin wallet address generated by the
UberPay wallet:

VoACszygLUt1JqpSL8PaS8xz2kz553t855

When I enter it on the block explorer

https://chainz.cryptoid.info/via/search.dws?q=VoACszygLUt1JqpSL8PaS8xz2kz553t855

I get a No match found result, is that something you seen before, or any
thoughts?

Adonis

On Wed, Sep 16, 2015 at 3:18 PM, ฿tcDrak notifications@github.com wrote:

> By eye, looks like feePerKb is wrong, should be 100000. Dust depends, but
> 1000 is way too small, more like 56000. spendableCoinbaseDepth is 3600.
> Come to #viacoin-dev on Freenode if you are having more difficulty.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/viacoin/viacoin/issues/36#issuecomment-140724784.

## 

Geopay.me Inc.

_"don't need to know everything, I just need to know where to find it."__A.
Einstein._
If you need to reach your people really fast, there's no better way to do
it than with "mobile".

Mobile is direct, accurate, and personal.

This email may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this email by mistake),
please notify the sender immediately and destroy this email. Any
unauthorised copying, disclosure or distribution of the material in this
email is strictly prohibited.

Email transmission security and error-free status cannot be guaranteed as
information could be intercepted, corrupted, destroyed, delayed,
incomplete, or contain viruses. The sender therefore does not accept
liability for any errors or omissions in the contents of this message
which may arise as a result of email transmission.
