### ISSUE TITLE
Add -maxuploadtarget feature

### ISSUE THREAD

**Issue by kha0S** [viacoin/viacoin-obsolete#47]
Hi.

Would it be possible to add the `-maxuploadtarget` option? I often see all my upload bandwidth being used by other peers downloading the blockchain.

Bitcoin PR is: https://github.com/bitcoin/bitcoin/pull/6622

**Comment by romanornr** [comment]
Hi, 

You are looking at the wrong/old repository.
This is the repo I am working in https://github.com/romanornr/viacoin/tree/0.13-dev

and yes it has the -maxuploadtarget

**Comment by kha0S** [comment]
Perfect. Thank you!
