### ISSUE TITLE
Implement CHECKLOCKTIMEVERIFY

### ISSUE THREAD

**Issue by btcdrak** [viacoin/viacoin-obsolete#5]

**Comment by petertodd** [comment]
Challenge accepted!

**Comment by petertodd** [comment]
So as for what CHECKLOCKTIMEVERIFY is, basically it's a soft-fork implementable opcode I proposed awhile back that would redefine one of the OP_NOP's with the following behavior:

```
<nLockTime> CHECKLOCKTIMEVERIFY -> <nLockTime>
```

where nLockTime is treated the same way as the nLockTime field in a transaction. Basically this lets you make a specific txout unspendable _until_ a certain time or block height in the future. This is useful for a number of things, like escrows, provably sacrificing coins to miners fees, payments for publishing data, etc.

I wrote up an implementation of it awhile back: https://github.com/petertodd/bitcoin/tree/op-checknlocktime I don't think I actually tested it - it was just a code exercise - but it should be pretty close to what we actually need modulo testing.

**Comment by btcdrak** [comment]
Things to think about:

The RPC must return the spend-ability of the transaction. Our block explorers will need to be updated with this information because up to know the assumption is if a tx is confirmed, it's spendable. Exchanges will need a way to test spend-ability.

**Comment by petertodd** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

That's no different than any other question of spendability; CHECKLOCKTIMEVERIFY isn't special in that regard. The rule always is you only consider scripts that you recognise as spendable, if the script isn't something you recognise you don't try to guess whether or not it might be possible to spend.

On 1 September 2014 04:45:41 GMT-04:00, "฿tcDrak" notifications@github.com wrote:

> Things to think about:
> 
> The RPC must return the spend-ability of the transaction. Our block
> explorers will need to be updated with this information because up to
> know the assumption is if a tx is confirmed, it's spendable. Exchanges
> will need a way to test spend-ability.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/viacoin/viacoin/issues/5#issuecomment-54035179
> -----BEGIN PGP SIGNATURE-----
> Version: APG v1.1.1

iQFQBAEBCAA6BQJUBDN9MxxQZXRlciBUb2RkIChsb3cgc2VjdXJpdHkga2V5KSA8
cGV0ZUBwZXRlcnRvZGQub3JnPgAKCRAZnIM7qOfwhWDWB/wPWA2+0I9/FhFB4Upj
UDoyzypBGyIbXgR49VXBLba1ceGgcJ3yJQ2WI6a5/Id9JLAwfo+tjTiBsWbq/nis
jijmGooCxaDhHcRjrTKLPvSTzfXLhZWuKlsFBMpH3F72WuD4qkVdd7aTSbLGPnh8
grfjfSbATQz5+Dkj1VFRgodA+/0/kXlM+7jl5RgLNJeOYXjefpdCgNIe1Z0N7LxJ
VlOJqK8JitzEjcV0qouK8ComF4oMMQB1SChrLV/0z4j1fxyvjbYfC/igPUfao6IZ
apTNDNxZ/xSa1zsyqniESufnv5ZoQEhw4G3xXkG1oIj4bzJhP7rE0/IKzJCYZbjM
NcF0
=RlpT
-----END PGP SIGNATURE-----

**Comment by btcdrak** [comment]
Completed in #23
