### ISSUE TITLE
Sign release tags

### ISSUE THREAD

**Issue by btcdrak** [viacoin/viacoin-obsolete#9]
The original tags were not signed, so they should be signed.

This will probably have some side effects at github which will show tags being newly made.

**Comment by petertodd** [comment]
When you sign them, it'd be good if they were of the format "viacoin-<version>" for clarity if you haven't already.

**Comment by btcdrak** [comment]
Do you mean the the tag name or the annotation?

**Comment by petertodd** [comment]
The tagname, same way https://github.com/petertodd/python-bitcoinlib is signed:

```
git tag -s viacoin-v0.10.foo <commit>
```

**Comment by btcdrak** [comment]
Interesting. I've always used a `v` prefix+semver.

What's the advantage of adding the package name prefix?

**Comment by petertodd** [comment]
Thing is the tag signature covers the tag name, so by adding the package name you better specify what exactly you are signing rather than leaving it ambiguous. This can be useful for certificate transparency systems.

Secondly, there's the pragmatic issue that it prevents tags from conflicting if you ever add both viacoin and bitcoin/etc. remotes to the same repo.

**Comment by btcdrak** [comment]
OK.

OT: I've been using `git fetch -n` to prevent pulling `bitcoin` repo tags.

**Comment by petertodd** [comment]
FWIW You can set a "don't import tags" bit on a per-remote basis with the --no-tags option of git remote add. I use that myself with repos that import python-bitcoinlib as a subtree - although now that I prefix the python-bitcoinlib tags with 'python-bitcoinlib-' I'll admit I've tended to let lazy about actually using that option. :)

**Comment by btcdrak** [comment]
Apparently just add `tagopt = --no-tags` to the `.git/config` e.g.

```
[remote "bitcoin"]
    url = https://github.com/bitcoin/bitcoin
    fetch = +refs/heads/*:refs/remotes/bitcoin/*
    tagopt = --no-tags
```
